# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/sol/ides/clion-2020.3.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/sol/ides/clion-2020.3.1/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sol/git_ws/TurretSystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sol/git_ws/TurretSystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/sol/ides/clion-2020.3.1/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sol/git_ws/TurretSystem/CMakeFiles /home/sol/git_ws/TurretSystem/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sol/git_ws/TurretSystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TurretSystemSubClasses

# Build rule for target.
TurretSystemSubClasses: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TurretSystemSubClasses
.PHONY : TurretSystemSubClasses

# fast build rule for target.
TurretSystemSubClasses/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/build
.PHONY : TurretSystemSubClasses/fast

#=============================================================================
# Target rules for targets named turretSystem

# Build rule for target.
turretSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 turretSystem
.PHONY : turretSystem

# fast build rule for target.
turretSystem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/turretSystem.dir/build.make CMakeFiles/turretSystem.dir/build
.PHONY : turretSystem/fast

#=============================================================================
# Target rules for targets named dense_optical_flow4

# Build rule for target.
dense_optical_flow4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dense_optical_flow4
.PHONY : dense_optical_flow4

# fast build rule for target.
dense_optical_flow4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dense_optical_flow4.dir/build.make CMakeFiles/dense_optical_flow4.dir/build
.PHONY : dense_optical_flow4/fast

#=============================================================================
# Target rules for targets named calibrate

# Build rule for target.
calibrate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calibrate
.PHONY : calibrate

# fast build rule for target.
calibrate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/build
.PHONY : calibrate/fast

apps/dense_optical_flow4.o: apps/dense_optical_flow4.cpp.o

.PHONY : apps/dense_optical_flow4.o

# target to build an object file
apps/dense_optical_flow4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dense_optical_flow4.dir/build.make CMakeFiles/dense_optical_flow4.dir/apps/dense_optical_flow4.cpp.o
.PHONY : apps/dense_optical_flow4.cpp.o

apps/dense_optical_flow4.i: apps/dense_optical_flow4.cpp.i

.PHONY : apps/dense_optical_flow4.i

# target to preprocess a source file
apps/dense_optical_flow4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dense_optical_flow4.dir/build.make CMakeFiles/dense_optical_flow4.dir/apps/dense_optical_flow4.cpp.i
.PHONY : apps/dense_optical_flow4.cpp.i

apps/dense_optical_flow4.s: apps/dense_optical_flow4.cpp.s

.PHONY : apps/dense_optical_flow4.s

# target to generate assembly for a file
apps/dense_optical_flow4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dense_optical_flow4.dir/build.make CMakeFiles/dense_optical_flow4.dir/apps/dense_optical_flow4.cpp.s
.PHONY : apps/dense_optical_flow4.cpp.s

src/Eye.o: src/Eye.cpp.o

.PHONY : src/Eye.o

# target to build an object file
src/Eye.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/Eye.cpp.o
.PHONY : src/Eye.cpp.o

src/Eye.i: src/Eye.cpp.i

.PHONY : src/Eye.i

# target to preprocess a source file
src/Eye.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/Eye.cpp.i
.PHONY : src/Eye.cpp.i

src/Eye.s: src/Eye.cpp.s

.PHONY : src/Eye.s

# target to generate assembly for a file
src/Eye.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/Eye.cpp.s
.PHONY : src/Eye.cpp.s

src/InverseForwardKinematicsModel.o: src/InverseForwardKinematicsModel.cpp.o

.PHONY : src/InverseForwardKinematicsModel.o

# target to build an object file
src/InverseForwardKinematicsModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/InverseForwardKinematicsModel.cpp.o
.PHONY : src/InverseForwardKinematicsModel.cpp.o

src/InverseForwardKinematicsModel.i: src/InverseForwardKinematicsModel.cpp.i

.PHONY : src/InverseForwardKinematicsModel.i

# target to preprocess a source file
src/InverseForwardKinematicsModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/InverseForwardKinematicsModel.cpp.i
.PHONY : src/InverseForwardKinematicsModel.cpp.i

src/InverseForwardKinematicsModel.s: src/InverseForwardKinematicsModel.cpp.s

.PHONY : src/InverseForwardKinematicsModel.s

# target to generate assembly for a file
src/InverseForwardKinematicsModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/InverseForwardKinematicsModel.cpp.s
.PHONY : src/InverseForwardKinematicsModel.cpp.s

src/PixelToMotorStepsConverter.o: src/PixelToMotorStepsConverter.cpp.o

.PHONY : src/PixelToMotorStepsConverter.o

# target to build an object file
src/PixelToMotorStepsConverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/PixelToMotorStepsConverter.cpp.o
.PHONY : src/PixelToMotorStepsConverter.cpp.o

src/PixelToMotorStepsConverter.i: src/PixelToMotorStepsConverter.cpp.i

.PHONY : src/PixelToMotorStepsConverter.i

# target to preprocess a source file
src/PixelToMotorStepsConverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/PixelToMotorStepsConverter.cpp.i
.PHONY : src/PixelToMotorStepsConverter.cpp.i

src/PixelToMotorStepsConverter.s: src/PixelToMotorStepsConverter.cpp.s

.PHONY : src/PixelToMotorStepsConverter.s

# target to generate assembly for a file
src/PixelToMotorStepsConverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/PixelToMotorStepsConverter.cpp.s
.PHONY : src/PixelToMotorStepsConverter.cpp.s

src/Serial_Rs232.o: src/Serial_Rs232.cpp.o

.PHONY : src/Serial_Rs232.o

# target to build an object file
src/Serial_Rs232.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/Serial_Rs232.cpp.o
.PHONY : src/Serial_Rs232.cpp.o

src/Serial_Rs232.i: src/Serial_Rs232.cpp.i

.PHONY : src/Serial_Rs232.i

# target to preprocess a source file
src/Serial_Rs232.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/Serial_Rs232.cpp.i
.PHONY : src/Serial_Rs232.cpp.i

src/Serial_Rs232.s: src/Serial_Rs232.cpp.s

.PHONY : src/Serial_Rs232.s

# target to generate assembly for a file
src/Serial_Rs232.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/Serial_Rs232.cpp.s
.PHONY : src/Serial_Rs232.cpp.s

src/StepperMotorController.o: src/StepperMotorController.cpp.o

.PHONY : src/StepperMotorController.o

# target to build an object file
src/StepperMotorController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/StepperMotorController.cpp.o
.PHONY : src/StepperMotorController.cpp.o

src/StepperMotorController.i: src/StepperMotorController.cpp.i

.PHONY : src/StepperMotorController.i

# target to preprocess a source file
src/StepperMotorController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/StepperMotorController.cpp.i
.PHONY : src/StepperMotorController.cpp.i

src/StepperMotorController.s: src/StepperMotorController.cpp.s

.PHONY : src/StepperMotorController.s

# target to generate assembly for a file
src/StepperMotorController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/StepperMotorController.cpp.s
.PHONY : src/StepperMotorController.cpp.s

src/TurretSystem.o: src/TurretSystem.cpp.o

.PHONY : src/TurretSystem.o

# target to build an object file
src/TurretSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/TurretSystem.cpp.o
.PHONY : src/TurretSystem.cpp.o

src/TurretSystem.i: src/TurretSystem.cpp.i

.PHONY : src/TurretSystem.i

# target to preprocess a source file
src/TurretSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/TurretSystem.cpp.i
.PHONY : src/TurretSystem.cpp.i

src/TurretSystem.s: src/TurretSystem.cpp.s

.PHONY : src/TurretSystem.s

# target to generate assembly for a file
src/TurretSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/TurretSystem.cpp.s
.PHONY : src/TurretSystem.cpp.s

src/calib_intrinsic.o: src/calib_intrinsic.cpp.o

.PHONY : src/calib_intrinsic.o

# target to build an object file
src/calib_intrinsic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/src/calib_intrinsic.cpp.o
.PHONY : src/calib_intrinsic.cpp.o

src/calib_intrinsic.i: src/calib_intrinsic.cpp.i

.PHONY : src/calib_intrinsic.i

# target to preprocess a source file
src/calib_intrinsic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/src/calib_intrinsic.cpp.i
.PHONY : src/calib_intrinsic.cpp.i

src/calib_intrinsic.s: src/calib_intrinsic.cpp.s

.PHONY : src/calib_intrinsic.s

# target to generate assembly for a file
src/calib_intrinsic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calibrate.dir/build.make CMakeFiles/calibrate.dir/src/calib_intrinsic.cpp.s
.PHONY : src/calib_intrinsic.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/turretSystem.dir/build.make CMakeFiles/turretSystem.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/turretSystem.dir/build.make CMakeFiles/turretSystem.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/turretSystem.dir/build.make CMakeFiles/turretSystem.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/motionDetector.o: src/motionDetector.cpp.o

.PHONY : src/motionDetector.o

# target to build an object file
src/motionDetector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/motionDetector.cpp.o
.PHONY : src/motionDetector.cpp.o

src/motionDetector.i: src/motionDetector.cpp.i

.PHONY : src/motionDetector.i

# target to preprocess a source file
src/motionDetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/motionDetector.cpp.i
.PHONY : src/motionDetector.cpp.i

src/motionDetector.s: src/motionDetector.cpp.s

.PHONY : src/motionDetector.s

# target to generate assembly for a file
src/motionDetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TurretSystemSubClasses.dir/build.make CMakeFiles/TurretSystemSubClasses.dir/src/motionDetector.cpp.s
.PHONY : src/motionDetector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TurretSystemSubClasses"
	@echo "... calibrate"
	@echo "... dense_optical_flow4"
	@echo "... turretSystem"
	@echo "... apps/dense_optical_flow4.o"
	@echo "... apps/dense_optical_flow4.i"
	@echo "... apps/dense_optical_flow4.s"
	@echo "... src/Eye.o"
	@echo "... src/Eye.i"
	@echo "... src/Eye.s"
	@echo "... src/InverseForwardKinematicsModel.o"
	@echo "... src/InverseForwardKinematicsModel.i"
	@echo "... src/InverseForwardKinematicsModel.s"
	@echo "... src/PixelToMotorStepsConverter.o"
	@echo "... src/PixelToMotorStepsConverter.i"
	@echo "... src/PixelToMotorStepsConverter.s"
	@echo "... src/Serial_Rs232.o"
	@echo "... src/Serial_Rs232.i"
	@echo "... src/Serial_Rs232.s"
	@echo "... src/StepperMotorController.o"
	@echo "... src/StepperMotorController.i"
	@echo "... src/StepperMotorController.s"
	@echo "... src/TurretSystem.o"
	@echo "... src/TurretSystem.i"
	@echo "... src/TurretSystem.s"
	@echo "... src/calib_intrinsic.o"
	@echo "... src/calib_intrinsic.i"
	@echo "... src/calib_intrinsic.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/motionDetector.o"
	@echo "... src/motionDetector.i"
	@echo "... src/motionDetector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

